language: generic
sudo: required
dist: trusty

matrix:
  fast_finish: true

  include:
    - os: linux
      compiler: 'python3.6'
      addons:
        apt:
          sources: ['deadsnakes']
          packages: ['python3.6', 'python3.6-dev', 'python3.6-tk', 'python3.6-venv', 'build-essential', 'libboost-python-dev', 'libexpat1-dev', 'zlib1g-dev', 'libbz2-dev', 'libspatialindex-dev']

before_install:
  - sudo update-alternatives --install /usr/bin/python3 python3 /usr/bin/python3.6 10
  - python3 -m venv .env && . .env/bin/activate

install:
  - python -m pip install http://download.pytorch.org/whl/cpu/torch-0.4.0-cp36-cp36m-linux_x86_64.whl
  - python -m pip install -r deps/requirements-lock.txt --quiet

script:
  - python -m pytest
  - python -m pip install flake8==3.5.0
  - flake8 robosat
